### PR TITLE
Use Hass.io Options

### PR DESCRIPTION
**Pull request by EmileSpecs**
This allows the Config class to also load the options from the options.json file created for add-ons.

Note however that the config.json file that defines the add-on repository must be modified:
the `options` and `schema` properties must be populated with the properties accepted by the PAI add-on.
(see https://github.com/EmileSpecs/hassio-repository/blob/master/paradox_alarm_interface/config.json)

### CODE REVIEW

**Comment by yozik04** [comment]
Please remove `.vs/*` from the repo

**Comment by yozik04** [comment]
Definitely Like!

**Comment by yozik04** [comment]
And we have a rule. Firstly we add stuff to `dev` branch. Then if it is stable, we merge it to master.

**Comment by EmileSpecs** [comment]
Sorry, I'm a total noob at Github.
Hope I've done everything correctly now...

**Comment by yozik04** [comment]
😆 You can stop. You ruined pull request...
I'll pick your changes manually.

**Comment by EmileSpecs** [comment]
Oh jeez, didn't think anything I do further would continue to influence this pull request! 
How do I "disconnect" my master from continuing to add commits to this pull request?!

**Comment by yozik04** [comment]
You can not 😄 
This is why it is good practice to do every feature in a separate branch.

**Comment by yozik04** [comment]
And if you willing to develop something please branch from `dev`!

**Comment by EmileSpecs** [comment]
Can you remove this pull request?

**Comment by yozik04** [comment]
Removing = Closing

**Pull request closed without merging**
