### PR TITLE
Merge to Master

### PR DESCRIPTION
**Pull request by Maxime-Drivet**

### CODE REVIEW

**Comment by yozik04** [comment]
I do not think it is worth to wait 1.5 seconds until panel replies. Usual time is under 200ms.So if it did not reply within 500ms I consider it won’t reply and I retry the attempt.Jevgeni24 февр. 2024 г., в 22:29, sonarcloud[bot] ***@***.***> написал(а):﻿
 Quality Gate passed
Issues
 0 New issues
Measures
 0 Security Hotspots
 No data about Coverage
 0.0% Duplication on New Code
See analysis details on SonarCloud

**Comment by yozik04** [comment]
@Maxime-Drivet 
I dot think it is worth to wait 1.5 seconds. If panel does not reply within 500ms then it won't reply. Average reply comes in under 200ms.

**Comment by Maxime-Drivet** [comment]
Thanks for your comment. I apologize for this accidental merge request. That’s for private test only.I operate a « very old » panel in v1.11 that usually fall in timeout except in one or two times in several days.Timeout occurs net in « Loading definitions » and « Updating Definitions from Panel » Or just after « Missing element with ID x in zone ». (Sometimes sooner, sometimes later)Last thing : Congrats for this job :)Envoyé de mon iPhoneLe 25 févr. 2024 à 08:24, Jevgeni Kiski ***@***.***> a écrit :﻿
@Maxime-Drivet
I dot think it is worth to wait 1.5 seconds. If panel does not reply within 500ms then it won't reply. Average reply comes in under 200ms.

**Comment by Maxime-Drivet** [comment]
Hello @yozik04 

I'm back on the send_wait delay :)
With standard delay at 0.5 sec, I always (most of the time) receive a TimeOut...

If I increase this delay, The panel load correctly with my old Panel.
Log :
`2024-03-03 10:03:18,413 - INFO     - PAI.paradox.paradox - Connecting to Panel

2024-03-03 10:03:18,511 - INFO     - PAI.paradox.paradox - Panel Identified $    version 1.11 build 3
2024-03-03 10:03:18,511 - INFO     - PAI.paradox.paradox - Initiating panel connection
2024-03-03 10:03:30,652 - INFO     - PAI.paradox.hardware.spectra_magellan.panel - Installer login
2024-03-03 10:03:30,757 - INFO     - PAI.paradox.hardware.spectra_magellan.panel - Authentication Success
2024-03-03 10:03:30,759 - INFO     - PAI.paradox.paradox - Connection OK
2024-03-03 10:03:30,759 - INFO     - PAI.paradox.paradox - Loading data from panel memory
2024-03-03 10:03:30,760 - INFO     - PAI.paradox.hardware.panel - Loading definitions
2024-03-03 10:03:30,761 - INFO     - PAI.paradox.hardware.panel - Updating Definitions from Panel
2024-03-03 10:03:43,192 - INFO     - PAI.paradox.hardware.panel - Zone definitions loaded (12.43s)
2024-03-03 10:03:43,581 - INFO     - PAI.paradox.hardware.panel - Pgm definitions loaded (0.39s)
2024-03-03 10:03:43,588 - INFO     - PAI.paradox.hardware.panel - Loading labels
2024-03-03 10:03:43,590 - INFO     - PAI.paradox.hardware.panel - Updating Labels from Panel
2024-03-03 10:03:43,877 - INFO     - PAI.paradox.hardware.panel - Zone labels loaded (0.29s): IR CELLIER, HALL ENTREE, SEJOUR, ETAGE, garage
2024-03-03 10:03:43,974 - INFO     - PAI.paradox.hardware.panel - Pgm labels loaded (0.1s): , 
2024-03-03 10:03:44,071 - INFO     - PAI.paradox.hardware.panel - Partition labels loaded (0.1s): AREA 1, AREA 2
2024-03-03 10:03:44,551 - INFO     - PAI.paradox.hardware.panel - User labels loaded (0.48s): , , , , , , , , , 
2024-03-03 10:03:44,551 - INFO     - PAI.paradox.hardware.panel - Module labels loaded (0.0s): 
2024-03-03 10:03:44,552 - INFO     - PAI.paradox.hardware.panel - Repeater labels loaded (0.0s): 
2024-03-03 10:03:44,553 - INFO     - PAI.paradox.hardware.panel - Keypad labels loaded (0.0s): 
2024-03-03 10:03:44,650 - INFO     - PAI.paradox.hardware.panel - Site labels loaded (0.1s): 
2024-03-03 10:03:44,847 - INFO     - PAI.paradox.hardware.panel - Siren labels loaded (0.2s): , , `


For now, it's difficult for me to properly build and test (test.yml) in VSCode (Got Error: Process completed with exit code 255)... And I broke the MQTT part.

But please consider an option to increase this timeout for older panels.
Thanks.

**Pull request closed without merging**
