### PR TITLE
Automatic build of a multi-arch Docker image with Travis CI (also for Raspberry Pi)

### PR DESCRIPTION
**Pull request by ivmarkov**
See #72.

A few notes: 
- This is a pull request for the master branch, but given that there are no changes of `.travis.yaml` in master vs dev, I think it can be pushed to all branches
- The approach taken is the one outlined [here](https://github.com/ParadoxAlarmInterface/pai/issues/72#issuecomment-557909602)
- I've tested the resulting image (master branch only) under arm32v7 (with latest Raspbian on RPI4) and on a regular x86_64 under Ubuntu Bionic. Both seem to work without issues (that is, putting asside some issues in the Python code itself with my EVOHD)
- The script is not only building the Docker image, but also pushing it to Docker Hub, on successful build
- The image will automatically have the regular "latest" tag if it is built from master, and for all other branches, it will have a "branch-name"-latest tag attached to it. E.g. if pushed to the dev branch, it will build an image with a tag "dev-latest"
- The Travis  configuration requires two (encrypted!) environment variables, DOCKER_USERNAME, and DOCKER_PASSWORD. You have to create these on the Travis Settings page. Make them available for all branches, and make sure that they are encrypted.
- If you assign as a DOCKER_USERNAME 'jpbarraca', the script WILL overwrite the existing jpbarraca/pai image in Docker Hub. That's probably what we want anyway, once you feel comfortable with the changes.
- Let me know if you plan to do versioned builds in future. We can figure out the proper Docker tags for that.

### CODE REVIEW

**Comment by ivmarkov** [comment]
If you are wondering why the checks failed - because the build is trying to use the aforementioned DOCKER_USERNAME & DOCKER_PASSWORD, and obviously you don't have them yet defined in the Travis Settings page, as per above.

**Comment by yozik04** [comment]
One issue with that. It tries to deploy pull requests.

**Comment by ivmarkov** [comment]
Should be easy to address with a Travis Conditional. Let me fix it & update the pull request.

**Comment by ivmarkov** [comment]
Done.

**Comment by ivmarkov** [comment]
Let me know if you would like (at least initially) the script to create an image with a different name than 'pai'. I can change it in the script, or I can introduce an environment variable for that.

**Comment by yozik04** [comment]
@ivmarkov Thank you very much!
I had to change your pull request to have a separate script file and better handling errors. After banging my head against my monitor with opened docker cli commands for around a half of the day now finally, based on your code, I managed to make travis automatically build multi-arch docker images and push them to the repo. Your contribution is registered in the README =)

Closing this pull request.

**Comment by ivmarkov** [comment]
Thanks a lot. I've looked at your changes quickly - all reasonable. Seems like collective heads-banging does miracles!

**Comment by jpbarraca** [comment]
Thanks for the help.

**Pull request closed without merging**
