### PR TITLE
Add SP6000+

### PR DESCRIPTION
**Pull request by carcinogoy**
New device uses 115200 baud rate over serial to communicate

### CODE REVIEW

**Comment by carcinogoy** [comment]
My bad bad commit

**Comment by yozik04** [comment]
@carcinogoy Did SP6000+ actually work for you? 
According to https://github.com/ParadoxAlarmInterface/pai/issues/334 seems that it did not.

**Comment by carcinogoy** [comment]
> @carcinogoy Did SP6000+ actually work with PAI? According to #334 seems that it did not.

Hi, mine works. I'm not currently home to get all the details. I'll post them when I get back.

General overview is
Raspberry Pi 3b+ 
USB CH343 jumper at 5v connected to the "top" serial port

**Comment by legsteve** [comment]
> > @carcinogoy Did SP6000+ actually work with PAI? According to #334 seems that it did not.
> 
> Hi, mine works. I'm not currently home to get all the details. I'll post them when I get back.
> 
> General overview is Raspberry Pi 3b+ USB CH343 jumper at 5v connected to the "top" serial port

Hi @carcinogoy 
Which SP6000+ firmware version do you use? I try on my side and I have trouble to communicate after the panel identification.

**Pull request merged**
